### ISSUE TITLE
Can't have "." in assembly prefix

### ISSUE THREAD

**Issue by photocyte** [blobtoolkit/insdc-pipeline#1]
Hi there,

Just a "trap for newbies". If you have a "." in your assembly.prefix name, that seems to screw up the pipeline w/ an unclear error. Example below for a prefix of `Pnm1.1b_ph1`:
 
```
Building DAG of jobs...
MissingInputException in line 23 of /lab/weng_scratch/Tim/20200404_Pnm_blobtools2_insdc-pipeline/insdc-pipeline/rules/blobtoolkit_add_hits.smk:
Missing input files for rule blobtoolkit_add_hits:
Pnm1.1b_ph1.diamond.reference_proteomes.root.1.minus..out
Pnm1.1b_ph1.blastn.nt.root.1.minus..out
```

Alternatively, renaming the assembly prefix to not include a "." fixes things:
```
mv Pnm1.1b_ph1.fasta Pnm11b_ph1.fasta
mv Pnm1.1b_ph1.yaml Pnm11b_ph1.yaml
cat Pnm11b_ph1.yaml | sed 's/Pnm1.1b_ph1/Pnm11b_ph1/g' > tmp
mv tmp Pnm11b_ph1.yaml
```
```
(snake_env) tfallon@tak /lab/weng_scratch/Tim/20200404_Pnm_blobtools2_insdc-pipeline/insdc-pipeline$   snakemake -p --use-conda \
>     --directory btk_workdir/ \
>     --configfile btk_workdir/Pnm11b_ph1.yaml \
>     -j 8 -R fetch_ncbi_db
```

And now it seems to be working:
```
Building DAG of jobs...
Creating conda environment ../envs/fetch.yaml...
Downloading and installing remote packages.
Environment for ../envs/fetch.yaml created (location: .snakemake/conda/7735f6b9)
Creating conda environment ../envs/pyblast.yaml...
Downloading and installing remote packages.
```
Thanks for making this pipeline & looking forward to using it & blobtools2 a bit more.

**Comment by photocyte** [comment]
Should mention, ran into a similar issue with underscores "_" in the the read names. The error was similarly cryptic.  E.g.:

This doesn't work:
```
reads:
  coverage:
    max: 100
    min: 0.5
  paired:
  - [L319_160_S1_L001 ILLUMINA, null, null]
  - [L319_160_S1_L002, ILLUMINA, null, null]
  - [L319_160_S1_L003, ILLUMINA, null, null]
  - [L319_160_S1_L004, ILLUMINA, null, null]
  - [L319_160_S1_L005, ILLUMINA, null, null]
  single: []
```

But after renaming the read files, this works:
```
reads:
  coverage:
    max: 100
    min: 0.5
  paired:
  - [L319l1, ILLUMINA, null, null]
  - [L319l2, ILLUMINA, null, null]
  - [L319l3, ILLUMINA, null, null]
  - [L319l4, ILLUMINA, null, null]
  - [L319l5, ILLUMINA, null, null]
  single: []
```
