### ISSUE TITLE
Snail Plot (Busco error)

### ISSUE THREAD

**Issue by Glenn032787** [blobtoolkit/insdc-pipeline#25]
Hello!

I used the blobtoolkits pipeline on one of the genomes. I used three lineages in the config file. Here is the busco section of my config file:
```
busco:
  download_dir: /projects/scratch/busco_lineage
  lineages:
    - sauropsida_odb10
    - tetrapoda_odb10
    - eukaryota_odb10
  basal_lineages:
    - sauropsida_odb10
    - tetrapoda_odb10
    - eukaryota_odb10
```
The issue is that the snail plot shows the busco for saudopsida_odb10 lineage in the top right hand corner with completion of 9455.3%, Frag. 38.2%, Dupl. 89.5% and Missing -9393.4%. I check the busco directory generated by the blobtoolkit and the busco scores seems normal. I am also viewing this from the snail.png file generated from blobtoolkits as I am having trouble getting the web viewer to work. Would you have any advice on how to resolve this issue. Thank you!
