### ISSUE TITLE
Pipeline fails: no Snakefile found, replaceHits error (v2.6.5)

### ISSUE THREAD

**Issue by gabbycoffing** [blobtoolkit/insdc-pipeline#26]
Hello! I'm having troubles getting the blobtools pipeline (v2.6.5) to run with a local assembly on a slurm cluster. It's unclear to me why this error is happening because I only find replaceHits and Snakefile in the v1 directory. Thank you!

Here is the error:

```
Error: no Snakefile found, tried Snakefile, snakefile, workflow/Snakefile, workflow/snakefile.
Error: no Snakefile found, tried Snakefile, snakefile, workflow/Snakefile, workflow/snakefile.
ERROR: failed during replaceHits
```

Here is my batch script: 
```
#!/bin/bash
#SBATCH --partition=kern 
#SBATCH --job-name=snakemake    
#SBATCH --output=blobtools_run_%j.out       
#SBATCH --error=blobtools_run_%j.err          
#SBATCH --time=01-0:00:00       
#SBATCH --nodes=1               
#SBATCH --ntasks-per-node=16     
#SBATCH -A kernlab

PIPELINE=/home/gcoffing/kernlab/genomeAssembly/outputs/blobtoolkit/insdc-pipeline
WORKDIR=/home/gcoffing/kernlab/genomeAssembly/outputs/blobtoolkit
CONDA_DIR=/home/gcoffing/kernlab/miniconda3/envs/blobtools/.conda
CLUSTER_DESTDIR=/home/gcoffing/kernlab/genomeAssembly/outputs/blobtoolkit/completed
PYTHONPATH=/home/gcoffing/kernlab/miniconda3/envs/blobtools/lib/python3.6/site-packages:$PYTHONPATH

THREADS=40
MULTICORE=8
MAXCORE=16

# Be sure to set the assembly name, this should match the YAML config filename
ASSEMBLY=contigsMiddlePurged.purged_HiC

# make sure conda activate is available in script
#eval "$(conda shell.bash hook)"

# activate the Conda environment
#mamba activate blobtools

TOOL=blobtoolkit
# Run snakemake
snakemake -p \
          --use-conda \
          --conda-prefix $CONDA_DIR \
          --directory $WORKDIR/$TOOL \
          --configfile /home/gcoffing/kernlab/genomeAssembly/outputs/blobtoolkit/config.yaml \
          --latency-wait 60 \
          --rerun-incomplete \
          --stats $ASSEMBLY/$TOOL.stats \
          -j $THREADS \
          -s $PIPELINE/$TOOL.smk \
          --resources btk=1

# Test for success
if [ $? -ne 0 ];then
  echo ERROR: failed during replaceHits
  exit 1
fi
```

Here is my config file: 
```
assembly:
  accession: draft
  level: scaffold
  prefix: contigsMiddlePurged.purged_HiC
  scaffold-count: 583
  span: 2345859994
  file: /home/gcoffing/kernlab/genomeAssembly/outputs/blobtoolkit/contigsMiddlePurged.purged_HiC.fasta
busco:
  lineage_dir: /home/gcoffing/kernlab/genomeAssembly/outputs/busco
  lineages:
    - metazoa_odb10
    - eukaryota_odb10
reads:
  single:
    - prefix: m64047_210118_165644.ccs
      platform: PACBIO_SMRT
      file: /home/gcoffing/kernlab/data/hifiCell1/4405/ccs.Q30/m64047_210118_165644.ccs.fastq.gz
    - prefix: m64047_210129_210448.ccs
      platform: PACBIO_SMRT
      file: /home/gcoffing/kernlab/data/hifiCell2/4406/ccs.Q30/m64047_210129_210448.ccs.fastq.gz
    - prefix: m64047_210131_031938.ccs
      platform: PACBIO_SMRT
      file: home/gcoffing/kernlab/data/hifiCell3/4407/ccs.Q30/m64047_210131_031938.ccs.fastq.gz
    - file: m64047_210620_170756.ccs
      platform: PACBIO_SMRT
      file: /home/gcoffing/kernlab/data/hifiCell4/4763/ccs.Q30/m64047_210620_170756.ccs.fastq.gz
    - prefix: m64047_210806_144628.ccs
      platform: PACBIO_SMRT
      file: /home/gcoffing/kernlab/data/hifiCell5/4764/ccs.Q30/m64047_210806_144628.ccs.fastq.gz
  coverage:
    max: 30
revision: 0
settings:
  blast_chunk: 100000
  blast_max_chunks: 10
  blast_overlap: 0
  blast_min_length: 1000
  taxdump: /home/gcoffing/kernlab/genomeAssembly/outputs/blobtoolkit/taxdump
  tmp: /tmp
similarity:
  defaults:
    evalue: 1.0e-10
    import_evalue: 1.0e-25
    max_target_seqs: 10
    taxrule: buscogenes
  diamond_blastx:
    name: reference_proteomes
    path: /home/gcoffing/kernlab/genomeAssembly/outputs/blobtoolkit/uniprot
  diamond_blastp:
    name: reference_proteomes
    path: /home/gcoffing/kernlab/genomeAssembly/outputs/blobtoolkit/uniprot
    import_max_target_seqs: 100000
  blastn:
    name: nt
    path: /home/gcoffing/kernlab/genomeAssembly/outputs/blobtoolkit/nt
taxon:
  name: Octopus bimaculoides
  taxid: '37653'
version: 2
```
